# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-11 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20200110_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='classes',
            field=models.ManyToManyField(related_name='classes', to='mall.Classify', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='mall.Tag', verbose_name='标签'),
        ),
    ]
