# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='登陆的账号')),
                ('ip', models.CharField(max_length=32, verbose_name='IP')),
                ('address', models.CharField(blank=True, max_length=32, null=True, verbose_name='地址')),
                ('source', models.CharField(max_length=32, verbose_name='登陆来源')),
                ('created_at', models.DateTimeField(verbose_name='登陆时间')),
            ],
            options={
                'db_table': 'account_login_record',
            },
        ),
        migrations.CreateModel(
            name='PasswdChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='用户头像')),
                ('integral', models.IntegerField(default=0, verbose_name='用户的积分')),
                ('level', models.SmallIntegerField(verbose_name='用户级别')),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('city', models.CharField(max_length=32, verbose_name='市区')),
                ('area', models.CharField(max_length=32, verbose_name='区域')),
                ('town', models.CharField(blank=True, max_length=32, null=True, verbose_name='街道')),
                ('address', models.CharField(max_length=64, verbose_name='详细地址')),
                ('username', models.CharField(max_length=32, verbose_name='收件人')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='accounts.User')),
            ],
            options={
                'db_table': 'account_user_address',
                'ordering': ['is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=32, verbose_name='真实姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮箱')),
                ('is_email_valid', models.BooleanField(default=False, verbose_name='邮箱是否已验证')),
                ('phone_no', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('is_phone_valid', models.BooleanField(default=False, verbose_name='手机号码是否已经验证')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('age', models.SmallIntegerField(default=0, verbose_name='年龄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
            options={
                'db_table': 'account_user_profile',
            },
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
