# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-10 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200110_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginrecord',
            options={'verbose_name': '登陆历史', 'verbose_name_plural': '登陆历史'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['is_default', '-updated_at'], 'verbose_name': '用户地址信息', 'verbose_name_plural': '用户地址信息'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户详细信息', 'verbose_name_plural': '用户详细信息'},
        ),
    ]
